server:
  port: 8088

spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  redis:
    database: 0 # Redis数据库索引（默认为0）
    host: 192.168.3.144 # Redis服务器地址
    port: 6379 # Redis服务器连接端口
    password: 123456 # Redis服务器连接密码（默认为空）
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 8  # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）




url:
  base:
    rest: http://rest.qtu.com #restful服务项目根地址
    search: http://search.qtu.com/search/query #search服务根地址
    sso: http://sso.qtu.com
  ad1:
    index: /api/content/33 #首页大广告地址
  items:
    item: /items/item/ #商品
    itemdesc: /items/itemdesc/  #商品描述
    itemparam: /items/itemparam/ #商品规格参数


cart:
  items:
    list:
      key: CART_ITEMS_LIST_KEY  #COOKIE中购物车商品对应的key
    expire:
      time: 1800  #购物车cookie生存期



#用户登录后保存的token name
QTU_USER_TOKEN: QTU_USER_TOKEN

#保存到redis中的用户购物车key
USER_CART_LIST_KEY: USER_CART_LIST_KEY

#cookie中储存session的key
SESSIONID: JSESSIONID

#订单服务系统url
ORDER_BASE_URL: http://order.qtu.com
#新加订单服务
ORDER_CREATE: /order/add