server:
 port: 8044   #项目的端口号

spring:
 #视图解析器
 mvc:
  view:
   prefix: /WEB-INF/jsp/
   suffix: .jsp
 datasource:
  type: com.alibaba.druid.pool.DruidDataSource #这里是配置druid连接池，以下都是druid的配置信息
  url: jdbc:mysql://192.168.3.144:3306/qtu_mall
  driver-class-name: com.mysql.jdbc.Driver
  username: root
  password: root
  druid:                                          # 进行数据库连接池的配置
   min-idle: 5                                   # 数据库连接池的最小维持连接数
   initial-size: 5                               # 初始化提供的连接数
   max-total: 5                                  # 最大的连接数
   max-wait-millis: 200                          # 等待连接获取的最大超时时间
 #redis
 redis:
  database: 0 # Redis数据库索引（默认为0）
  host: 192.168.3.144 # Redis服务器地址
  port: 6379 # Redis服务器连接端口
  password: 123456 # Redis服务器连接密码（默认为空）
  jedis:
   pool:
    max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
    max-idle: 8  # 连接池中的最大空闲连接
    min-idle: 0 # 连接池中的最小空闲连接
    max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）


# mybatis 配置
mybatis:
  mapper-locations: classpath*:mapping/*.xml #把xml文件放在com.XX.mapper.*中可能会出现找不到的问题，这里把他放在resource下的mapper中
  typeAliasesPackage: com.qtu.sso.entity #这里是实体类的位置，#实体扫描，多个package用逗号或者分号分隔

#显示sql
logging:
  level:
   com.qtu.sso.mapper: debug






